language: shell

env: GO_VERSION=1.4.2

before_install:
  # install golang
  - pushd ~/
  - curl -L -o go.tar.gz https://github.com/golang/go/archive/go${GO_VERSION}.tar.gz
  - tar xzf go.tar.gz
  - ls
  - mv go-go${GO_VERSION} go
  - export GOROOT=~/go
  - export GOPATH=~/gopath/
  - export PATH=$GOROOT/bin:$PATH
  - popd

  - pushd $GOROOT/src/
  - ./make.bash
  - popd

install:
  - go get github.com/mattn/go-lingr

script:
  - go version
  - go env
  - go test ./...
  # setup cross compiling environment
  - pushd `go env GOROOT`/src
  - GOOS=windows GOARCH=amd64 ./make.bash --no-clean
  - GOOS=windows GOARCH=386   ./make.bash --no-clean
  - GOOS=darwin  GOARCH=amd64 ./make.bash --no-clean
  - GOOS=darwin  GOARCH=386   ./make.bash --no-clean
  - GOOS=linux   GOARCH=amd64 ./make.bash --no-clean
  - GOOS=linux   GOARCH=386   ./make.bash --no-clean
  - popd
  # cross compile
  - mkdir ~/artifacts/
  - GOOS=windows GOARCH=amd64 go build lingr.go && cp lingr.exe ~/artifacts/lingr.win64.exe
  - GOOS=windows GOARCH=386   go build lingr.go && cp lingr.exe ~/artifacts/lingr.win32.exe
  - GOOS=darwin  GOARCH=amd64 go build lingr.go && cp lingr     ~/artifacts/lingr.mac64
  - GOOS=darwin  GOARCH=386   go build lingr.go && cp lingr     ~/artifacts/lingr.mac32
  - GOOS=linux   GOARCH=amd64 go build lingr.go && cp lingr     ~/artifacts/lingr.x64
  - GOOS=linux   GOARCH=386   go build lingr.go && cp lingr     ~/artifacts/lingr.x86

deploy:
  provider: releases

  api_key:
    secure: JYmyq6713NCL7S+HOH2cuW7y15AHjPzISpGqSDvhVm3znuE2m7BdkGxj0RzikXFuDd+unVe2pKw+sufm9R83Qsiu/E8LlEJbRnsm+LWqVGBw73SH1cU5qkMCf9XM7f/w8+WyFze4vyBHOkDyXazRlaRSFtE+KjHXQncQff1LyeY=

  file:
    - $HOME/artifacts/lingr.win64.exe
    - $HOME/artifacts/lingr.win32.exe
    - $HOME/artifacts/lingr.mac64
    - $HOME/artifacts/lingr.mac32
    - $HOME/artifacts/lingr.x64
    - $HOME/artifacts/lingr.x86

  on:
    tags: true
